version: '3.8'

services:
  devicems:
    build: ./deviceMs
    container_name: devicemspoc
    environment:
      - DAVRA_API_TOKEN=
    networks:
      - reverse-proxy-net

  twinms:
    build: ./twinMs
    container_name: twinmspoc
    environment:
      - DAVRA_API_TOKEN=
    networks:
      - reverse-proxy-net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./ngnixReverseProxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - reverse-proxy-net
    depends_on:
      - devicems
      - twinms

networks:
  reverse-proxy-net:
    driver: bridge
